### ISSUE TITLE
03-1: Ist *pop_back()* erforderlich?

### ISSUE THREAD

**Issue by MariusHerget** [fuchsto/cpppc-18#1]
Ist eine *pop_back()* implementation erforderlich? Wir sollen ja einen _ForwardIterator_ mit einer _single-linked-list_ kombinieren. Eine sinnvolle Implementierung von *pop_back()* wuerde aber eine _double-linked-list_ erfordern.

**Comment by fuchsto** [comment]
Nein, wir haben eine single-linked-list, also `std::forward_list`, siehe Iterator-Kategorie.
