### ISSUE TITLE
03-1: Unknown error message

### ISSUE THREAD

**Issue by MariusHerget** [fuchsto/cpppc-18#3]
When I try to initialize `list_node * _head       = { nullptr, default_value };` there is this error: `rrror: excess elements in scalar initializer`.

What is the meaning of this error and how can i resolve it?

**Comment by jakubo87** [comment]
_head ist bei dir ein Pointer. Ein Pointer hat nur einen Wert: eine Adresse.

**Comment by MariusHerget** [comment]
@jakubo87  hast du ein Beispiel für eine Lösung ohne Pointer? Das scheitert bei mir grad irgendwie die ganze Zeit.

Besonders bei *push_back*.

**Comment by fuchsto** [comment]
@MariusHerget 
Man braucht einen Pointer, aber den erhält man über `new list_node()`. Die Listenelemente werden ja auf dem Heap alloziert.
