### ISSUE TITLE
lazy_sequence container überhaupt ein container?

### ISSUE THREAD

**Issue by jakubo87** [fuchsto/cpppc-18#5]
Hallo
wie verhält sich ein LSC bei pop_front? soll er das haben? ist das nächste Element dann das selbe wie das dann letzte? oder soll i gespeichert werden und  für die instanz stetig erhöht werden?

Ein container der nichts speichert widerspricht ja dem concept eines containers. ein Algorithmus würde ja dann eigentlich reichen, der die eingabe i verwurstet und das ergebnis der funktion widergibt...

Was also muss er von seq_con können und was nicht?
ein container wäre er nur, wenn durch pop (front/back) werte rausfallen und dann nur durch erzeugung neuer (ggf in der mitte) neue erzeugt werden. Sollen dabei Duplikate entstehen können, je nach position? dürfen sich Sachen verschieben?

Bitte um Klärung! (zügig wäre mir lieb, da ich unter der Woche kaum mehr Zeit haben werde!)

**Comment by fuchsto** [comment]
Wie gestern besprochen: Nein, kann es auch gar nicht.
Siehe: http://en.cppreference.com/w/cpp/concept/SequenceContainer

Wie die Aufgabenstellung schon sagt:
`insert`, `emplace` etc. sind nicht möglich und nicht gefordert.

Uns interessiert hauptsächlich begin(), end(), size() und der Iterator (Random Access).
