### ISSUE TITLE
ein lambda fangen

### ISSUE THREAD

**Issue by jakubo87** [fuchsto/cpppc-18#7]
warum geht das (Quelle cppref):
    print_num(int i){std::cout<<i<<"n\";}

    std::function<void()> f_display_42 = []() { print_num(42); };
    f_display_42();

aber das hier nicht???
    lazy_sequence(const T size, std::function<T(int)>& f) 
>> candidate constructor not viable: no known conversion from '(lambda at lazy_sequence.cc:8:25)' to 'std::function<int (int)> &' for 2nd argument

**Comment by fuchsto** [comment]
@jakubo87 

Weil der Parameter `f` keine Referenz sein sollte.
Das Lambda wird ja als Temporary übergeben. Also: es existiert nicht mehr, sobald der Constructor-Scope verlassen wird.

Das hier geht, falls `param` nur innerhalb der Funktion (also: dem Scope von `foo`) verwendet wird:
~~~
void foo(const int & param);
foo(3);
~~~
Aber das auch nur, weil `const & T` zu einer by-value-Übergabe aufgelöst werden kann.
Das hier geht nicht:
~~~
void foo(int & param);
foo(3);
~~~
Weil das der Implementierung von foo erlauben würde, den referenzierten Wert zu ändern.
Also würde es das hier erlauben:
~~~
void foo(int & param) {
   param = 4;
}
foo(3);
~~~
Und da siehst du das Problem recht plastisch, glaube ich.

`std::function` ist bereits ein sehr leichtgewichtiges Objekt, das ist im Grunde schon selbst eine Referenz auf die Funktion. Immer by-value übergeben!
